/* Quantum Courier: original gameplay, no external libraries. */
'use strict';
const Q=Quantum,$=id=>document.getElementById(id);
const tutorials=[
 {title:'Nothing to hide',short:'Meet your key',brief:'Carry your key through scanner A, then reach the gold delivery pad. Step on a station to use it.',goal:'Deliver a Z-up key',note:'A matching scanner keeps the answer certain.',hint:'Your key starts Z-up. Walk right through the Z scanner and keep going to the gold pad.',start:'Z+',target:'Z+',stations:[{id:'A',x:5,y:3,type:'scan',mode:'Z',choices:['Z']}],lesson:'A matching measurement is predictable. Your Z-up key passed a Z scanner without changing.',floor:'straight'},
 {title:'The second look',short:'Measure twice',brief:'Scanner A asks a different question. Set B to repeat that question, then walk through A and B.',goal:'Make the second scan certain',note:'Either first result is fine. Predict the next one.',hint:'A measures X, which is random for a Z-up key. Set B to X too. The first scan prepares an X state; the second gives the same result.',start:'Z+',stations:[{id:'A',x:3,y:3,type:'scan',mode:'X',choices:['X']},{id:'B',x:6,y:3,type:'scan',mode:'Z',choices:['Z','X']}],lesson:'The first X scan was random, but it prepared an X state. Another X scan repeats the answer with certainty. A Z scan in between would disturb it.',floor:'straight'},
 {title:'Change, don’t check',short:'Meet a gate',brief:'A gate changes your key without reading it. Choose the gate that makes X-plus certain, then deliver.',goal:'Deliver an X-plus key',note:'Use one gate. No measurement needed.',hint:'Try the H gate. It transforms Z-up into X-plus. Look at both probability bars before and after.',start:'Z+',target:'X+',stations:[{id:'A',x:5,y:3,type:'gate',mode:'X',choices:['X','H','Z']}],lesson:'H transformed Z-up into X-plus without measuring it. Z readings are now 50/50, while X-plus is certain. A gate and a measurement do different jobs.',floor:'straight',budget:1},
 {title:'The invisible difference',short:'The final delivery',brief:'Build a three-gate route to Z-down. Watch the relative sign: a change invisible in the Z probabilities can still matter later.',goal:'Deliver Z-down, every time',note:'Three operations. H and Z gates only.',hint:'Try H, then Z, then H. The first H creates equal amplitudes. Z reverses their relative sign. The final H makes them interfere toward Z-down.',start:'Z+',target:'Z-',stations:[{id:'A',x:3,y:3,type:'gate',mode:'H',choices:['H','Z']},{id:'B',x:5,y:3,type:'gate',mode:'H',choices:['H','Z']},{id:'C',x:7,y:3,type:'gate',mode:'Z',choices:['H','Z']}],lesson:'H → Z → H sent the key to Z-down with certainty. Z changed the relative sign; the final H converted that phase difference into a different outcome. That is interference.',floor:'alcoves',budget:3}
];
simplifyTutorial(tutorials);
tutorials[0].budget=1;tutorials[1].budget=2;tutorials[1].echo=true;
const rooms=[...tutorials,...Levels.campaign,Levels.finale];
let current=0,completed=new Set(),stations=[],selected='A',run,history=[],sound=true,audio,relocating=false;
function freshRun(){const initial=Q.states[rooms[current].start].slice();return {x:1,y:3,hasKey:false,state:initial,branches:[{weight:1,state:initial.slice()}],ops:0,seen:[],scans:[],logs:[`Key prepared: ${Levels.names[rooms[current].start]}. Pick up the diamond on the next tile.`],won:false,message:'Move right onto the green diamond to collect your quantum key.',messageType:''};}
function start(index,keep=false){relocating=false;current=index;if(!keep)stations=rooms[index].stations.map(s=>({...s,choices:[...s.choices]}));selected=stations[0].id;run=freshRun();history=[];saveProgress();render();}
function restartRound(){completed.delete(current);start(current);}
function floor(x,y){if(rooms[current].tiles)return rooms[current].tiles.includes(`${x},${y}`);return y===3&&x>=1&&x<=9 || rooms[current].floor==='alcoves'&&(y===2||y===4)&&[1,2,4,6,8,9].includes(x);}
function at(x,y){return stations.find(s=>s.x===x&&s.y===y);}
function tone(freq=420){if(!sound)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(.045,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.14);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.15);}catch{}}
function say(text,type=''){run.message=text;run.messageType=type;}
function operate(s){if(!run.hasKey)return;run.event={before:run.state.slice(),type:s.type,mode:s.mode};run.ops++;run.seen.push(s.id);if(s.type==='scan'){
 const predictable=Q.certain(run.branches,s.mode),result=Q.measure(run.state,s.mode);
 run.event.outcome=result.outcome;run.state=result.state;run.branches=Q.ensembleMeasure(run.branches,s.mode);run.scans.push({id:s.id,basis:s.mode,certain:predictable,outcome:result.outcome});
 const label=reading(s.mode,result.outcome),chance=Math.round(result.probability*100);
 const text=`${s.id}: ${s.mode} scan → ${label}. ${chance}% chance before this reading.`;
 run.logs.unshift(text);say(chance===100?`${text} Repeating the same measurement preserves this result.`:`${text} The scanner changed the key into ${label}. Measure in this same basis again and this answer is certain.`);tone(chance===100?660:330);
 }else{run.state=Q.gate(run.state,s.mode);run.branches=Q.ensembleGate(run.branches,s.mode);const descriptions={H:'H rotates between Z and X states. No measurement took place.',X:'X swaps the Z-up and Z-down amplitudes. No measurement took place.',Z:'Z reverses the sign of the Z-down amplitude. Z-reading probabilities stay the same.'};run.logs.unshift(`${s.id}: ${s.mode} gate applied. ${descriptions[s.mode]}`);say(descriptions[s.mode]);tone(s.mode==='H'?520:390);}
 run.event.after=run.state.slice();run.logs=run.logs.slice(0,5);
}
function reading(b,i){return b==='Z'?(i?'Z-down':'Z-up'):(i?'X-minus':'X-plus');}
function delivery(){if(!run.hasKey){say('Pick up the quantum key before delivering.','warn');return;}const room=rooms[current],result=Levels.validate(room,run,Q);if(result.valid){run.won=true;run.explanationRead=false;completed.add(current);saveProgress();say(room.lesson,'win');run.logs.unshift('DELIVERY COMPLETE · This solution does not depend on luck.');tone(880);showDeliveryExplanation();}else{say(result.detail,'warn');tone(190);}}

function move(dx,dy){if(relocating){say('Choose an empty floor tile to place the selected station, or press Cancel move.');renderMessage();return;}if(run.won||$('modal').open)return;const x=run.x+dx,y=run.y+dy;if(!floor(x,y)){say('That is a wall. Follow the lit floor tiles.');renderMessage();return;}
 const station=at(x,y),budget=rooms[current].budget;if(station&&budget&&run.ops>=budget){say(`The key has used its ${budget}-operation budget. Undo or restart to try another route.`,'warn');renderMessage();return;}
 history.push(JSON.parse(JSON.stringify(run)));run.x=x;run.y=y;const collected=!run.hasKey&&x===2&&y===3;if(collected){run.hasKey=true;run.logs.unshift('KEY COLLECTED · You are now carrying one qubit.');tone(740);}if(station){selected=station.id;operate(station);}else if(x!==9||y!==3){say(run.ops?'Keep going to the gold delivery pad. You can undo a step at any time.':'Walk onto the first station to see what happens.');}
 if(collected)say('Key collected! The green diamond now travels with you. Walk onto a station to use it.');if(x===9&&y===3)delivery();render();
}
function undo(){if(history.length){run=history.pop();render();}}
function configure(mode){relocating=false;const s=stations.find(s=>s.id===selected);if(!s.choices.includes(mode)||s.mode===mode)return;s.mode=mode;const id=selected;run=freshRun();history=[];selected=id;say(`${s.type==='scan'?'Scanner':'Gate'} ${s.id} is now ${mode}. A fresh ${Levels.names[rooms[current].start]} key is ready at the entrance.`);render();}
function stateName(){for(const [k,v] of Object.entries(Q.states)){if(Math.abs(run.state[0]*v[0]+run.state[1]*v[1])>1-1e-9)return reading(k[0],k[1]==='+'?0:1);}return 'Quantum state';}
function render(){const room=rooms[current];renderNavigation();$('room-number').textContent=current<4?`TUTORIAL ${current+1} / 4`:current===30?'SANDBOX · YOUR CUSTOM PUZZLE':current===29?'BONUS FINALE · THE LAST QUANTUM KEY':`LEVEL ${String(current-3).padStart(2,'0')} / 25 · ${room.chapter}`;$('title').textContent=room.title;$('brief').textContent='';$('goal').textContent=room.echo?'Final result: a certain final scan':'Final result: '+Levels.names[room.target];$('goal-note').textContent=room.echo?'100% predictable for every earlier outcome.':'100% reliability';$('ops').textContent=`${run.ops}${room.budget?' / '+room.budget:''} operation${run.ops===1?'':'s'}`;
 let html='';for(let y=0;y<7;y++)for(let x=0;x<11;x++){const f=floor(x,y),s=at(x,y),player=run.x===x&&run.y===y,exit=x===9&&y===3;let content=s?`<span class="station-tag">${s.id}</span><span class="station-symbol">${s.mode}</span>`:exit?'<span class="exit-mark">⇥</span>':'';if(!run.hasKey&&x===2&&y===3)content+='<span class="floor-key" aria-hidden="true">◆</span>';if(player)content+=`<span class="courier ${run.hasKey?'carrying':''}" aria-hidden="true"></span>`;const desc=!f?'Wall':!run.hasKey&&x===2&&y===3?'Quantum key pickup':s?`${s.optional?'Optional hazard scanner':s.type==='scan'?'Scanner':'Gate'} ${s.id}, ${s.mode}${s.choices.length>1?', select to configure':''}`:exit?'Delivery pad':x===1&&y===3?'Entrance':'Floor';html+=f?`<button tabindex="${relocating?0:-1}" class="tile ${s?'station '+(s.optional?'hazard ':'')+(s.type==='scan'?'scanner ':'')+(selected===s.id?'selected ':''):''}${exit?'exit ':''}${x===1&&y===3?'start ':''}${s&&run.seen.includes(s.id)?'visited':''}" data-x="${x}" data-y="${y}" aria-label="${desc}${player?', courier here':''}">${content}</button>`:'<div class="tile wall" aria-hidden="true"></div>';}$('board').innerHTML=html;
 renderStateOrbit();$('state-name').textContent=run.hasKey?stateName():'Collect your key';$('state-caption').textContent=run.hasKey?'Carrying one quantum key':'Diamond on the next tile · preview below';$('probabilities').innerHTML=['Z','X'].map(b=>{const p=Math.round(Q.probability(run.state,b)*100);return `<div class="prob-row"><div class="prob-label"><strong>${b} scanner</strong><span>${p===0||p===100?'Certain':'Random'}</span></div><div class="prob-track"><span style="width:${p}%"></span></div><div class="prob-values"><span>${reading(b,0)} ${p}%</span><span>${reading(b,1)} ${100-p}%</span></div></div>`;}).join('');const [a,b]=run.state;$('phase').textContent=Math.abs(a*b)<1e-9?'One amplitude only':a*b<0?'Opposite (+ / −)':'Same (+ / +)';
 $('equipment').innerHTML=stations.map(s=>`<button class="${selected===s.id?'selected':''}" data-select="${s.id}" aria-label="Inspect station ${s.id}">${s.id} · ${s.mode}</button>`).join('');renderStation();$('log').innerHTML=run.logs.slice(0,3).map(l=>`<li>${l}</li>`).join('');$('undo').disabled=!history.length;renderMessage();renderReplay(run.event||null);renderTutorialGuide();
}
function renderStation(){const s=stations.find(s=>s.id===selected);$('station-detail').innerHTML=`<strong>${s.type==='scan'?'Scanner':'Gate'} ${s.id}</strong> · ${s.type==='scan'?'Reads the key and changes its state.':'Changes the key without reading it.'}${s.choices.length>1?`<div class="mode-buttons">${s.choices.map(m=>`<button data-mode="${m}" class="${s.mode===m?'chosen':''}" aria-pressed="${s.mode===m}">${m}${s.type==='scan'?' basis':' gate'}</button>`).join('')}</div>`:'<p class="micro">Fixed station mode for this room.</p>'}${current>0&&!s.locked?`<button id="relocate" style="margin-top:10px;width:100%;font-size:13px">${relocating?'Cancel move':'Move this station'}</button>`:''}`;}
function deliverySummary(){
 const room=rooms[current];
 const required=room.echo?'A certain final scan for every earlier outcome (either first reading is allowed)':Levels.names[room.target]+' with 100% reliability';
 const actual=run.hasKey?stateName():'No key collected';
 const reliability=room.echo?(run.scans.length>=2&&run.scans.at(-1).certain?'Final scan is certain':'Final scan is not yet guaranteed'):run.hasKey?Math.round(Q.fidelity(run.branches,Q.states[room.target])*100)+'% of possible outcomes reach '+Levels.names[room.target]:'Collect the key first';
 return '<div class="delivery-summary"><p><strong>Required at the gold pad:</strong> '+required+'.</p><p><strong>You delivered this run:</strong> '+actual+'.</p><p><strong>Your route:</strong> '+reliability+'. A single result is different from a guaranteed solution.</p></div>';
}
function renderMessage(){$('message').className='message '+run.messageType;$('message').innerHTML=`<div><strong>${run.won?'Delivery complete. ':run.messageType==='warn'?'Not quite. ':''}</strong>${run.message}${run.x===9&&run.y===3?deliverySummary():''}</div>${run.won&&run.explanationRead?`<button class="primary" id="next">${current===3?'Start campaign':current===28?'Enter finale':current===29?'Finish adventure':current<3?'Next tutorial':'Next level'}</button>`:''}`;}
function modal(content){$('modal').returnValue='';$('modal-content').innerHTML=content;$('modal').showModal();}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.id==='tutorial-mode'){start(0);return;}if(b.id==='campaign-mode'){start(4);return;}if(b.dataset.level!==undefined){start(Number(b.dataset.level));return;}if(b.dataset.select){relocating=false;selected=b.dataset.select;render();return;}if(b.dataset.mode){configure(b.dataset.mode);return;}if(b.dataset.move){move(...b.dataset.move.split(',').map(Number));return;}if(b.dataset.x!==undefined){const x=+b.dataset.x,y=+b.dataset.y,s=at(x,y);if(relocating){if(!s && x!==1 && x!==9){const moving=stations.find(v=>v.id===selected);moving.x=x;moving.y=y;relocating=false;run=freshRun();history=[];say('Station moved. A fresh key is ready. Walk your new route.');render();}else{say('Choose an empty floor tile, away from the entrance and delivery pad.');renderMessage();}return;}if(s){selected=s.id;render();}else if(Math.abs(x-run.x)+Math.abs(y-run.y)===1)move(x-run.x,y-run.y);else{say('Use WASD, arrow keys, or the direction buttons to walk. Select stations to configure them.');renderMessage();}return;}
 if(b.id==='relocate'){relocating=!relocating;say(relocating?'Choose an empty lit floor tile to move this station. The run will restart.':'Station move cancelled.');renderStation();renderMessage();}if(b.id==='undo')undo();if(b.id==='restart')restartRound();if(b.id==='hint'){say(rooms[current].hint);renderMessage();}if(b.id==='next')advanceRound();

 if(b.id==='sound'){sound=!sound;b.textContent=sound?'Sound on':'Sound off';b.setAttribute('aria-pressed',String(sound));tone();}if(b.id==='close-modal')$('modal').close($('modal').dataset.delivery==='true'?'continue':'dismiss');if(b.id==='help')showWelcome();if(b.id==='science')modal('<h2>The physics inside the puzzle</h2><p>One pure qubit is represented by two amplitudes: <code>α|0⟩ + β|1⟩</code>. This game uses real amplitudes because H, X and Z preserve real states; it does not simulate every possible qubit phase.</p><p><strong>Z measurement:</strong> outcome probabilities are α² and β². <strong>X measurement:</strong> probabilities are (α + β)²/2 and (α − β)²/2. The state collapses to the eigenstate of the observed result.</p><p><strong>H:</strong> (α, β) becomes ((α + β)/√2, (α − β)/√2). <strong>X:</strong> swaps amplitudes. <strong>Z:</strong> changes the sign of β.</p><p>“Z-up/down” mean |0⟩/|1⟩, and “X-plus/minus” mean |+⟩/|−⟩. These are teaching labels for states, not physical directions in the map.</p><p>The game samples individual scans using the Born rule and separately tracks <strong>all possible branches</strong>. A lucky reading cannot satisfy a guarantee puzzle. This is a classical simulation, with no entanglement or quantum hardware.</p>');});
document.addEventListener('keydown',e=>{if(document.getElementById('game-screen').hidden)return;if(['SELECT','INPUT','TEXTAREA'].includes(e.target.tagName))return;if($('modal').open||e.ctrlKey||e.altKey||e.metaKey)return;const key=e.key.toLowerCase(),dirs={arrowup:[0,-1],w:[0,-1],arrowdown:[0,1],s:[0,1],arrowleft:[-1,0],a:[-1,0],arrowright:[1,0],d:[1,0]};if(dirs[key]){e.preventDefault();if(!e.repeat)move(...dirs[key]);}if(key==='u'){e.preventDefault();undo();}if(key==='r'){e.preventDefault();restartRound();}});
try{const saved=JSON.parse(localStorage.getItem('quantum-courier-progress-v2')||'null');if(saved){completed=new Set(saved.completed.filter(i=>Number.isInteger(i)&&i>=0&&i<rooms.length));current=Number.isInteger(saved.current)&&saved.current>=0&&saved.current<rooms.length?saved.current:0;}}catch{}
start(current);

function saveProgress(){try{localStorage.setItem('quantum-courier-progress-v2',JSON.stringify({current,completed:[...completed]}));}catch{}}
function renderNavigation(){if(current===30){$('levels').innerHTML='<button id="edit-custom-puzzle" aria-label="Back to sandbox editor">← Back to sandbox</button>';$('chapter-control').hidden=true;return;}const tutorial=current<4,chapter=tutorial?0:Math.floor((current-4)/5),first=tutorial?0:4+chapter*5,count=tutorial?4:5;$('tutorial-mode').setAttribute('aria-pressed',String(tutorial));$('campaign-mode').setAttribute('aria-pressed',String(!tutorial));$('chapter-control').hidden=tutorial;$('chapter').value=String(chapter);$('campaign-progress').textContent=`${[...completed].filter(i=>i>=4&&i<29).length} / 25 · Finale ${completed.has(29)?'✓':'○'}`;$('levels').innerHTML=rooms.slice(first,first+count).map((r,j)=>{const i=first+j;return `<button data-level="${i}" class="${i===current?'active':''}" ${i===current?'aria-current="step"':''}><span class="number">${tutorial?'T'+(i+1):String(i-3).padStart(2,'0')}</span>${r.short}<span class="check">${completed.has(i)?'✓':''}</span></button>`;}).join('');}
document.getElementById('chapter').addEventListener('change',e=>start(4+Number(e.target.value)*5));

function showDeliveryExplanation(){const room=rooms[current];const label=room.echo?'Your final scan was predictable for every possible earlier outcome.':`Your route delivered ${Levels.names[room.target]} with 100% reliability.`;modal(`<div class="eyebrow">DELIVERY COMPLETE</div><h2>${current===29?'Congratulations!':'Why your route worked'}</h2>${current===29?'<p>You completed the final challenge and delivered the last quantum key!</p>':''}<p><strong>${label}</strong></p>${deliverySummary()}<p>${room.lesson}</p><p class="small">You started with ${Levels.names[room.start]} and used ${run.ops} operation${run.ops===1?'':'s'}. The visual replay below the board lets you inspect the last change.</p>`);$('close-modal').textContent=current===30?'Back to workshop':'Continue';$('modal').dataset.delivery='true';}
document.getElementById('modal').addEventListener('close',()=>{const delivery=$('modal').dataset.delivery==='true',advance=delivery&&$('modal').returnValue==='continue';delete $('modal').dataset.delivery;$('close-modal').textContent='Got it';if(delivery&&run.won){run.explanationRead=true;if(advance)advanceRound();else renderMessage();}});

function advanceRound(){if(current===30){openSandbox();return;}if(current===29){openSandbox();return;}if(current<rooms.length-1)start(current+1);else modal(`<div class="eyebrow">FINALE CLEARED</div><h2>Congratulations, Quantum Courier!</h2><p>You completed the final challenge and delivered the last quantum key.</p><p>You combined gates, measurement and interference to complete the final challenge.</p><p>You have completed <strong>${[...completed].filter(i=>i>=4&&i<29).length} of 25 campaign levels</strong>.</p><p>Use the chapter selector to revisit any unfinished deliveries. The four tutorial rooms are always available.</p><p>Explain your discovery: why does changing a measurement basis affect certainty, and how can a sign change alter the final result?</p>`);}

showHome();

function renderStateOrbit(){const [a,b]=run.state,x=2*a*b,z=a*a-b*b,px=50+31*x,py=50-31*z,el=document.querySelector('.key-orbit');el.removeAttribute('aria-hidden');el.setAttribute('role','img');el.setAttribute('aria-label',`Qubit state diagram: ${stateName()}. Horizontal X axis, vertical Z axis.`);el.innerHTML=`<svg viewBox="0 0 100 100" aria-hidden="true"><circle cx="50" cy="50" r="33" fill="#e7efff" stroke="#c0d1ef"/><ellipse cx="50" cy="50" rx="33" ry="12" fill="none" stroke="#c0d1ef" stroke-dasharray="3 3"/><path d="M50 17V83M17 50H83" stroke="#b0c1df"/><path d="M50 50L${px} ${py}" stroke="#2961cb" stroke-width="2.5"/><circle cx="${px}" cy="${py}" r="5" fill="#2961cb" stroke="white" stroke-width="2"/><circle cx="50" cy="50" r="2.5" fill="#7a99ce"/><text x="50" y="10" text-anchor="middle" fill="#45628c" font-size="10">Z</text><text x="91" y="54" text-anchor="middle" fill="#45628c" font-size="10">X</text></svg>`;}

function setTheme(theme){document.documentElement.dataset.theme=theme;document.getElementById('theme-toggle').textContent=theme==='dark'?'Light mode':'Dark mode';document.getElementById('theme-toggle').setAttribute('aria-pressed',String(theme==='dark'));try{localStorage.setItem('qc-theme',theme);}catch{}}
function showHome(){document.getElementById("sandbox-screen")?.setAttribute("hidden","");document.getElementById('home-screen').hidden=false;document.getElementById('game-screen').hidden=true;document.getElementById('home-progress').textContent=`Your progress: ${[...completed].filter(i=>i>=4&&i<29).length} of 25 campaign deliveries complete.`;}
function openGame(index,welcome=false){document.getElementById("sandbox-screen")?.setAttribute("hidden","");document.getElementById('home-screen').hidden=true;document.getElementById('game-screen').hidden=false;start(index);if(welcome)showWelcome();}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.id==='theme-toggle')setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');if(b.id==='home-button')showHome();if(b.id==='start-over'){completed.clear();openGame(0,true);}if(['home-tutorial','home-lessons'].includes(b.id))openGame(0,true);if(b.id==='home-campaign')openGame(4);if(b.id==='home-resume'){document.getElementById('home-screen').hidden=true;document.getElementById('game-screen').hidden=false;render();}if(b.id==='home-rules')showWelcome();});
setTheme(document.documentElement.dataset.theme||'light');

// A separate circuit workshop: the campaign state stays intact.
const sandbox=document.createElement('section');
sandbox.id='sandbox-screen';sandbox.hidden=true;sandbox.className='sandbox-panel';
const stateOptions=Object.entries(Levels.names).map(([v,n])=>`<option value="${v}">${n}</option>`).join('');
const operationOptions='<option value="none">Empty</option><option value="H">H · Mix gate</option><option value="X">X · Flip gate</option><option value="Z">Z · Phase gate</option><option value="scanZ">Measure Z</option><option value="scanX">Measure X</option>';
sandbox.innerHTML=`<div class="eyebrow">YOUR QUANTUM WORKSHOP</div><h1>Make your own problem</h1><p>Choose a starting key and a goal. Arrange up to five operations from left to right, then test your circuit. Can you reach your goal every time?</p><div class="sandbox-settings"><label>Starting key<select id="sandbox-start">${stateOptions}</select></label><label>Required output<select id="sandbox-target">${stateOptions}</select></label></div><div class="sandbox-circuit">${Array.from({length:5},(_,i)=>`<label>Station ${i+1}<select id="sandbox-op-${i}">${operationOptions}</select></label>`).join('')}</div><p>H mixes the Z and X states. X flips Z-up and Z-down. Z changes their relative sign. Scanners read the key and may change it.</p><div class="home-actions"><button id="sandbox-run" class="primary">Test my problem</button><button id="sandbox-reset">Clear circuit</button><button id="sandbox-home">Back home</button></div><div id="sandbox-result" role="status" aria-live="polite">Your draft is saved in this browser. Try Z-up → X gate → Z-down for a first problem.</div>`;
document.getElementById('game-screen').after(sandbox);
const sandboxHome=document.createElement('button');sandboxHome.id='home-sandbox';sandboxHome.textContent='Sandbox · Create a problem';document.querySelector('.home-actions').append(sandboxHome);
function openSandbox(){document.getElementById('home-screen').hidden=true;document.getElementById('game-screen').hidden=true;sandbox.hidden=false;window.scrollTo(0,0);}
function sandboxDraft(){return {start:$('sandbox-start').value,target:$('sandbox-target').value,ops:Array.from({length:5},(_,i)=>$('sandbox-op-'+i).value)};}
function saveSandbox(){try{localStorage.setItem('qc-sandbox-v1',JSON.stringify(sandboxDraft()));}catch{}}
try{const d=JSON.parse(localStorage.getItem('qc-sandbox-v1'));if(d&&Q.states[d.start]&&Q.states[d.target]&&Array.isArray(d.ops)){$('sandbox-start').value=d.start;$('sandbox-target').value=d.target;d.ops.slice(0,5).forEach((v,i)=>{if(['none','H','X','Z','scanZ','scanX'].includes(v))$('sandbox-op-'+i).value=v;});}}catch{}
sandbox.addEventListener('change',()=>{saveSandbox();$('sandbox-result').textContent='Circuit changed. Test again to see its new output.';});
function testSandbox(){const d=sandboxDraft();let state=Q.states[d.start].slice(),branches=[{weight:1,state:state.slice()}];const steps=[];const name=v=>Object.keys(Q.states).find(k=>Math.abs(v[0]*Q.states[k][0]+v[1]*Q.states[k][1])>1-1e-9);d.ops.forEach((op,i)=>{if(op==='none')return;if(op.startsWith('scan')){const basis=op.slice(4);state=Q.measure(state,basis).state;branches=Q.ensembleMeasure(branches,basis);}else{state=Q.gate(state,op);branches=Q.ensembleGate(branches,op);}steps.push(`<li>Station ${i+1}: ${op.startsWith('scan')?'Measure '+op.slice(4):op+' gate'} → ${Levels.names[name(state)]}</li>`);});const p=Q.fidelity(branches,Q.states[d.target]);$('sandbox-result').innerHTML=`<h2>${p>1-1e-9?'Problem solved — guaranteed!':'Keep experimenting'}</h2><p><strong>Required:</strong> ${Levels.names[d.target]} every time.<br><strong>This run:</strong> ${Levels.names[name(state)]}.<br><strong>Reliability:</strong> ${Math.round(p*100)}%.</p><ol>${steps.join('')}</ol><p>${p>1-1e-9?'Your circuit reaches the goal for every possible measurement outcome. Change the goal or operations to create another challenge.':'A lucky result is not enough. Change a gate or scanner and test again. Some circuits cannot guarantee the selected goal.'}</p>`;saveSandbox();}
document.addEventListener('click',e=>{const id=e.target.closest('button')?.id;if(id==='home-sandbox')openSandbox();if(id==='sandbox-run')testSandbox();if(id==='sandbox-home')showHome();if(id==='sandbox-reset'){for(let i=0;i<5;i++)$('sandbox-op-'+i).value='none';saveSandbox();$('sandbox-result').textContent='Circuit cleared. Choose your operations and test again.';}});

// Visual station editor and a playable custom courier room.
const workshopBoard=document.createElement('div');workshopBoard.className='workshop-board';workshopBoard.setAttribute('aria-label','Custom puzzle board preview');
sandbox.querySelector('.sandbox-circuit').before(workshopBoard);
const playCustom=document.createElement('button');playCustom.id='sandbox-play';playCustom.className='primary';playCustom.textContent='Play my puzzle';sandbox.querySelector('.home-actions').prepend(playCustom);
function renderWorkshopBoard(){const d=sandboxDraft();workshopBoard.innerHTML='<div class="workshop-tile">🤖<small>Start</small></div><div class="workshop-tile">◆<small>'+Levels.names[d.start]+' key</small></div>'+d.ops.map((op,i)=>'<button class="workshop-tile '+(op.startsWith('scan')?'workshop-scan':op==='none'?'':'workshop-gate')+'" data-workshop-slot="'+i+'" aria-label="Edit station '+(i+1)+'">'+(op==='none'?'+':op.startsWith('scan')?'◉ '+op.slice(4):op)+'<small>Station '+(i+1)+'</small></button>').join('')+'<div class="workshop-tile workshop-goal">⚑<small>'+Levels.names[d.target]+'</small></div>';}
function playCustomPuzzle(){const d=sandboxDraft(),customStations=d.ops.flatMap((op,i)=>op==='none'?[]:[{id:String.fromCharCode(65+i),x:i+3,y:3,type:op.startsWith('scan')?'scan':'gate',mode:op.startsWith('scan')?op.slice(4):op,choices:[op.startsWith('scan')?op.slice(4):op],locked:true}]);if(!customStations.length){$('sandbox-result').textContent='Place at least one gate or scanner on the board before playing.';return;}
 rooms[30]={title:'Your quantum delivery',short:'Custom puzzle',chapter:'Workshop',start:d.start,target:d.target,stations:customStations,budget:customStations.length,floor:'straight',goal:'Deliver '+Levels.names[d.target]+', every time',note:'Visit every station · '+customStations.length+' operations max',brief:'Walk right to collect your key, pass through your stations, and reach the gold pad. Use Edit my puzzle to change the board.',hint:'Return to the workshop to change the gates, scanners or required output. Test my problem checks whether your circuit guarantees the target.',lesson:'Your custom circuit delivers the required state for every possible measurement outcome.'};completed.delete(30);saveSandbox();openGame(30);}
sandbox.addEventListener('change',renderWorkshopBoard);
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.workshopSlot!==undefined){const input=$('sandbox-op-'+b.dataset.workshopSlot);input.focus();input.scrollIntoView({block:'nearest',behavior:'smooth'});}if(b.id==='sandbox-play')playCustomPuzzle();if(b.id==='edit-custom-puzzle')openSandbox();if(b.id==='sandbox-reset')renderWorkshopBoard();});
renderWorkshopBoard();

// Capture button activation so navigation controls share the sound preference.
document.addEventListener('click',e=>{const button=e.target.closest('button');if(button&&!button.disabled&&button.id!=='sound')tone(560);},true);

$('sound').textContent='Sound on';$('sound').setAttribute('aria-pressed','true');
