'use strict';
let lastReplay='';
function replayName(v){for(const [name,state] of Object.entries(Quantum.states)){if(Math.abs(v[0]*state[0]+v[1]*state[1])>1-1e-9)return { 'Z+':'Z-up','Z-':'Z-down','X+':'X-plus','X-':'X-minus'}[name];}return 'Quantum key';}
function replayCard(v,label){return `<div class="replay-state"><span class="replay-label">${label}</span><strong>${replayName(v)}</strong><div class="amplitudes">${v.map((a,i)=>`<div class="amplitude-row"><span>${i?'Down':'Up'}</span><div class="amplitude-track"><i class="${a<0?'negative':''}" style="width:${Math.abs(a)*48}%;${a<0?'right':'left'}:50%"></i></div><b>${Math.abs(a)<1e-9?'0':(a<0?'−':'+')+Math.abs(a).toFixed(2)}</b></div>`).join('')}</div><div class="replay-probs">${['Z','X'].map(b=>`<span>${b} scan <b>${Math.round(Quantum.probability(v,b)*100)} / ${Math.round((1-Quantum.probability(v,b))*100)}%</b></span>`).join('')}</div></div>`;}
function renderReplay(event){const el=document.getElementById('visual-replay');const signature=JSON.stringify(event);if(signature===lastReplay)return;lastReplay=signature;if(!event){el.innerHTML='<div class="replay-heading"><strong>See the change</strong><span>VISUAL REPLAY</span></div><p class="replay-empty">Walk onto a station. See your key before and after, and why it changed.</p>';return;}
const isScan=event.type==='scan';let explanation;if(isScan){const p=Quantum.probability(event.before,event.mode,event.outcome);explanation=p>1-1e-9?'This answer was already certain. The matching scan preserved the state.':'The scan chose one outcome using these probabilities, then prepared that outcome’s state. Another scan in the same basis will repeat it.';}else if(event.mode==='Z'){explanation=Math.abs(event.before[0]*event.before[1])>1e-9?'Z flipped the down amplitude’s sign. The Z probabilities stayed the same, but the X probabilities changed. A later H can turn this sign difference into a different Z result.':'Z flipped the down amplitude’s sign. With only one nonzero amplitude, this does not change any measurement probability.';}else if(event.mode==='H'){explanation='H adds and subtracts the two amplitudes. Matching signs reinforce one result; opposite signs cancel it. This is a transformation, not a measurement.';}else{explanation='X swapped the up and down amplitudes. The key changed without being measured.';}
el.innerHTML=`<div class="replay-heading"><strong>What just happened?</strong><button id="replay-animation" aria-label="Replay last operation animation">Replay</button></div><div class="replay-flow animate-replay">${replayCard(event.before,'1 · BEFORE')}<div class="replay-operation"><span class="replay-arrow" aria-hidden="true">→</span><strong>${event.mode}</strong><span>${isScan?'measurement':'gate'}</span><span class="replay-arrow" aria-hidden="true">→</span></div>${replayCard(event.after,'2 · AFTER')}</div>${isScan?`<div class="outcome-title">Possible readings before this scan</div><div class="replay-outcomes">${[0,1].map(i=>`<div class="replay-outcome ${i===event.outcome?'observed':''}"><span>${event.mode==='Z'?(i?'Z-down':'Z-up'):(i?'X-minus':'X-plus')}</span><strong>${Math.round(Quantum.probability(event.before,event.mode,i)*100)}%</strong><small>${i===event.outcome?'✓ Observed this time':'Not observed'}</small></div>`).join('')}</div>`:''}<p class="replay-explanation">${explanation}</p><p class="replay-footnote">Bars show signed amplitudes, not probabilities. Z: up / down. X: plus / minus. Replay repeats the illustration, not the measurement.</p>`;
}
document.addEventListener('click',e=>{if(!e.target.closest('#replay-animation'))return;const flow=document.querySelector('.replay-flow');flow.classList.remove('animate-replay');void flow.offsetWidth;flow.classList.add('animate-replay');});
